CREATE TABLE "user"
(
  id            BIGINT AUTO_INCREMENT PRIMARY KEY,
  username      VARCHAR(255) NOT NULL,
  email         VARCHAR(255) NOT NULL UNIQUE,
  password      VARCHAR(255) NOT NULL,
  creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
