CREATE TABLE note
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT,
  FOREIGN KEY (user_id) REFERENCES "user"(id)
);
